version: "3.7"
services:
  mariadb:
    container_name: notes_db
    image: mariadb:10.7
    restart: unless-stopped
    networks:
      - easy-notes-network
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: notes-api

networks:
  easy-notes-network:
    driver: bridge